version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .docker-compose.env

  social:
    build:
      context: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    command: >
      bash -c "alembic revision --autogenerate -m "init" &&
               alembic upgrade head &&
               uvicorn src.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .docker-compose.env
    depends_on:
      - db