"""likes

Revision ID: 729baf0d17f3
Revises: 7ffd7a1e1e0e
Create Date: 2023-07-24 19:25:10.065569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729baf0d17f3'
down_revision = '7ffd7a1e1e0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_Likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posts_likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='posts_likes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_likes_pkey')
    )
    op.drop_table('posts_Likes')
    # ### end Alembic commands ###
