"""sec

Revision ID: 77b26313c499
Revises: 7ff156aedb10
Create Date: 2023-07-24 18:55:03.904206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b26313c499'
down_revision = '7ff156aedb10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_dislikes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_dislikes_owner_id_fkey', 'posts_dislikes', type_='foreignkey')
    op.create_foreign_key(None, 'posts_dislikes', 'users', ['user_id'], ['id'])
    op.drop_column('posts_dislikes', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_dislikes', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts_dislikes', type_='foreignkey')
    op.create_foreign_key('posts_dislikes_owner_id_fkey', 'posts_dislikes', 'users', ['owner_id'], ['id'])
    op.drop_column('posts_dislikes', 'user_id')
    # ### end Alembic commands ###
