"""sec

Revision ID: 7ff156aedb10
Revises: 41d0a0c69881
Create Date: 2023-07-24 18:44:37.335307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff156aedb10'
down_revision = '41d0a0c69881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('posts_dislikes_post_id_fkey', 'posts_dislikes', type_='foreignkey')
    op.create_foreign_key(None, 'posts_dislikes', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts_dislikes', type_='foreignkey')
    op.create_foreign_key('posts_dislikes_post_id_fkey', 'posts_dislikes', 'users', ['post_id'], ['id'])
    op.drop_table('posts_likes')
    # ### end Alembic commands ###
