"""abc2

Revision ID: b92e4d4778f5
Revises: 1ed354efd774
Create Date: 2023-07-24 19:09:08.814605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92e4d4778f5'
down_revision = '1ed354efd774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
